### ISSUE TITLE
[PATCH] Fix JACK plugin buffer sizes

### ISSUE THREAD

**Issue by zoidby** [alsa-project/alsa-plugins#12] opened 2020-08-02 11:00 UTC
The jack plugin wasn’t working for me and [adenosine on the archlinux forum](https://bbs.archlinux.org/viewtopic.php?pid=1870631#p1870631) found the bug and wrote a patch for me.

[adenosine already posted it to the alsa-devel mailing list](https://mailman.alsa-project.org/pipermail/alsa-devel/2019-October/157480.html), but it hasn’t been applied so far.

**Comment by aditpape** [comment] 2021-02-16 16:10
Hi @zoidby ,
analysis in archlinux forum is stating the issue is related to the fact, that jack plugin allows only period sizes matching (multiples of) the JACK-daemon period size
>>The problem is while the jack plugin enforces the period to be a multiple of the frame size
My current open PR #14  (https://github.com/alsa-project/alsa-plugins/pull/14) is addressing such an issue by allowing unaligned period size (which was the default for many years...).
Would be fine if you could also test whether that may solve your issue.. (then you need to add option align_psize = 0 in asound.conf )
Regards,
Andreas

**Comment by zoidby** [comment] 2021-02-16 17:16
I don’t know how to apply your patch. »patch -p0 -i "$srcdir/14.patch"« gives me:
```
can't find file to patch at input line 20
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 26bdc2a1a284cf3c09976a1be0df5673dee093df Mon Sep 17 00:00:00 2001
|From: Andreas Pape <apape@de.adit-jv.com>
|Date: Tue, 24 Nov 2020 16:48:03 +0100
|Subject: [PATCH] jack: add option to allow non-jack-aligned period size
|
|Commit 72337f1dcb2df6a2b7fdae93e88d7dd3a7e97ab4 forces ALSA period size
|to be exact multiple of the JACK daemon period size.
|There are good reasons to align the period size, but completely disallowing non aligned periods is too restrictive.
|This patch adds an option "align_psize" which allows to optionally revert to original behavior.
|
|Signed-off-by: Andreas Pape <apape@de.adit-jv.com>
|---
| jack/pcm_jack.c | 18 +++++++++++++++---
| 1 file changed, 15 insertions(+), 3 deletions(-)
|
|diff --git a/jack/pcm_jack.c b/jack/pcm_jack.c
|index 5dc78fb..26674fa 100644
|--- a/jack/pcm_jack.c
|+++ b/jack/pcm_jack.c
--------------------------
File to patch: 

```

**Comment by aditpape** [comment] 2021-02-17 07:32
Hi,
when calling from within alsa-plugins source directory -p1 is required.
cd alsa-plugins/
patch -p1 -i ~/<path_to_patch>/add-option-to-allow-non-jack-aligned-period-size.patch

Do you have a buildable source tree for alsa-plugins available?


Andreas

**Comment by zoidby** [comment] 2021-02-17 11:47
Yep, that works.

And your patch fixes the problem as well.

**Comment by aditpape** [comment] 2021-02-17 11:51
THX for testing and confirmation...

**Comment by zoidby** [comment] 2021-02-17 11:58
Thanks for bringing additional additional attention to this.

The original bug was discovered and fixed in 2019. I hope one of these patches gets applied some day. It’s annoying having to maintain my own version of this package.

**Comment by perexg** [comment] 2021-05-25 15:39
The mentioned patch looks like a workaround for some hidden bug. It would be nice to analyze the issue and fix it in alsa-lib.

The patch from @aditpape was accepted, so I'm closing this now.

**Closed by perexg** 2021-05-25 15:39 UTC
